<!DOCTYPE html>
<html> 
	<head>
		<style data-styles="">ion-icon{visibility:hidden}.hydrated{visibility:inherit}</style>

		<meta charset="utf-8">
		<!-- Title -->
		<title>Smartboard</title>

		<!--- Favicon --->
		<link rel="icon" href="mt/assets//img/brand/favicon.png" type="image/x-icon">

		<!--- Icons css --->
		<link href="mt/assets//css/icons.css" rel="stylesheet">

		<!--- Right-sidemenu css --->
		<link href="mt/assets//plugins/sidebar/sidebar.css" rel="stylesheet">

		<!--- Custom Scroll bar --->
		<link href="mt/assets//plugins/mscrollbar/jquery.mCustomScrollbar.css" rel="stylesheet">

		<!--- Style css --->
		<link href="mt/assets//css/style.css" rel="stylesheet">
		<link href="mt/assets//css/skin-modes.css" rel="stylesheet">

		<!--- Sidemenu css --->
		<link href="mt/assets//css/sidemenu2.css" rel="stylesheet">

		<!--- Animations css --->
		<link href="mt/assets//css/animate.css" rel="stylesheet">

	<script src="https://smarthela.com/user/assets//plugins/ionicons/ionicons/ionicons.suuqn5vt.js" type="module" crossorigin="true" data-resources-url="https://smarthela.com/user/assets//plugins/ionicons/ionicons/" data-namespace="ionicons"></script><style type="text/css">/* Chart.js */
@-webkit-keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}@keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}.chartjs-render-monitor{-webkit-animation:chartjs-render-animation 0.001s;animation:chartjs-render-animation 0.001s;}</style><style type="text/css" id="s./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./package/src/animation.scss-0">/**
 * @license
 * Copyright Akveo. All Rights Reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 */
.eva-animation {
  animation-duration: 1s;
  animation-fill-mode: both; }

.eva-infinite {
  animation-iteration-count: infinite; }

.eva-icon-shake {
  animation-name: eva-shake; }

.eva-icon-zoom {
  animation-name: eva-zoomIn; }

.eva-icon-pulse {
  animation-name: eva-pulse; }

.eva-icon-flip {
  animation-name: eva-flipInY; }

.eva-hover {
  display: inline-block; }

.eva-hover:hover .eva-icon-hover-shake, .eva-parent-hover:hover .eva-icon-hover-shake {
  animation-name: eva-shake; }

.eva-hover:hover .eva-icon-hover-zoom, .eva-parent-hover:hover .eva-icon-hover-zoom {
  animation-name: eva-zoomIn; }

.eva-hover:hover .eva-icon-hover-pulse, .eva-parent-hover:hover .eva-icon-hover-pulse {
  animation-name: eva-pulse; }

.eva-hover:hover .eva-icon-hover-flip, .eva-parent-hover:hover .eva-icon-hover-flip {
  animation-name: eva-flipInY; }

@keyframes eva-flipInY {
  from {
    transform: perspective(400px) rotate3d(0, 1, 0, 90deg);
    animation-timing-function: ease-in;
    opacity: 0; }
  40% {
    transform: perspective(400px) rotate3d(0, 1, 0, -20deg);
    animation-timing-function: ease-in; }
  60% {
    transform: perspective(400px) rotate3d(0, 1, 0, 10deg);
    opacity: 1; }
  80% {
    transform: perspective(400px) rotate3d(0, 1, 0, -5deg); }
  to {
    transform: perspective(400px); } }

@keyframes eva-shake {
  from,
  to {
    transform: translate3d(0, 0, 0); }
  10%,
  30%,
  50%,
  70%,
  90% {
    transform: translate3d(-3px, 0, 0); }
  20%,
  40%,
  60%,
  80% {
    transform: translate3d(3px, 0, 0); } }

@keyframes eva-pulse {
  from {
    transform: scale3d(1, 1, 1); }
  50% {
    transform: scale3d(1.2, 1.2, 1.2); }
  to {
    transform: scale3d(1, 1, 1); } }

@keyframes eva-zoomIn {
  from {
    opacity: 1;
    transform: scale3d(0.5, 0.5, 0.5); }
  50% {
    opacity: 1; } }
</style><style type="text/css">.jqstooltip { position: absolute;left: 0px;top: 0px;visibility: hidden;background: rgb(0, 0, 0) transparent;background-color: rgba(0,0,0,0.6);filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000);-ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000)";color: white;font: 10px arial, san serif;text-align: left;white-space: nowrap;padding: 5px;border: 1px solid white;box-sizing: content-box;z-index: 10000;}.jqsfield { color: white;font: 10px arial, san serif;text-align: left;}</style>
</head><body class="main-body app sidebar-mini sidebar-gone">

		<!-- Loader -->
		<div id="global-loader" style="display: none;">
			<img src="assets//img/loaders/loader-4.svg" class="loader-img" alt="Loader">
		</div>
		<!-- /Loader -->



		<!-- page -->
	<div class="page">

		<!-- main-sidebar opened -->
		          <div class="app-sidebar__overlay" data-toggle="sidebar"></div>
		<aside class="main-sidebar app-sidebar sidebar-scroll ps ps--active-y">
			<div class="main-sidebar-header">
				<a class="desktop-logo logo-light active" href="index.html"><img src="assets//img/brand/logo.png" class="main-logo"></a>
				<a class="desktop-logo icon-logo active" href="index.html"><img src="assets//img/brand/favicon.png" class="logo-icon"></a>
				<a class="desktop-logo logo-dark active" href="index.html"><img src="assets//img/brand/logo-white.png" class="main-logo dark-theme" alt="logo"></a>
				<a class="logo-icon mobile-logo icon-dark active" href="index.html"><img src="assets//img/brand/favicon-white.png" class="logo-icon dark-theme" alt="logo"></a>
			</div><!-- /logo -->
			<div class="main-sidebar-loggedin">
				<div class="app-sidebar__user">
					<div class="dropdown user-pro-body text-center">
						<div class="user-pic">
							<img src="assets//img/faces/6.jpg" alt="user-img" class="rounded-circle mCS_img_loaded">
						</div>
						<div class="user-info">
							<h6 class=" mb-0 text-dark" style="text-transform:capitalize;">sting</h6>
							<span class="text-muted app-sidebar__user-name text-sm">Premium User</span>
						</div>
					</div>
				</div>
			</div>
			<div class="sidebar-navs">
				<ul class="nav  nav-pills-circle">
					<li class="nav-item" data-toggle="tooltip" data-placement="top" title="" data-original-title="Settings" aria-describedby="tooltip365540">
						<a href="myprofile.php" class="nav-link text-center m-2">
							<i class="fe fe-settings"></i>
						</a>
					</li>
					<li class="nav-item" data-toggle="tooltip" data-placement="top" title="" data-original-title="Chat">
						<a class="nav-link text-center m-2">
							<i class="fe fe-mail"></i>
						</a>
					</li>
					<li class="nav-item" data-toggle="tooltip" data-placement="top" title="" data-original-title="Followers">
						<a class="nav-link text-center m-2">
							<i class="fe fe-user"></i>
						</a>
					</li>
					<li class="nav-item" data-toggle="tooltip" data-placement="top" title="" data-original-title="Logout">
						<a href="logout.php" class="nav-link text-center m-2">
							<i class="fe fe-power"></i>
						</a>
					</li>
				</ul>
			</div>
			<div class="main-sidebar-body">
				<ul class="side-menu ">
					<li class="slide active">
						<a class="side-menu__item active" href="dashboard.php"><i class="side-menu__icon fe fe-airplay"></i><span class="side-menu__label">Dashboard</span></a>
					</li>
					<li class="slide">
						<a class="side-menu__item" href="deposit.php"><i class="side-menu__icon fe fe-database"></i><span class="side-menu__label">Deposit</span></a>
					</li>
				    <li class="slide">
						<a class="side-menu__item" href="../payforclient"><i class="side-menu__icon fe fe-command"></i><span class="side-menu__label">PayForClient</span></a>
					</li>
				
					<li class="slide">
						<a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fe fe-box"></i><span class="side-menu__label">Withdrawals</span><i class="angle fe fe-chevron-down"></i></a>
						<ul class="slide-menu">
							<li><a class="slide-item" href="withdraw.php">BalanceWithdraw</a></li>
							<li><a class="slide-item" href="withdrawyoutube.php">YoutubeWithdraw</a></li>
							<li><a class="slide-item" href="withdrawblog.php">BlogWithdraw</a></li>
							<li><a class="slide-item" href="withdrawtrivia.php">TriviaWithdraw</a></li>
							<li><a class="slide-item" href="withdrawalhistory.php">WithdrawalHistory</a></li>
						</ul>
					</li>
				   
				    <li class="slide">
						<a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fe fe-users"></i><span class="side-menu__label">MyTeam</span><i class="angle fe fe-chevron-down"></i></a>
						<ul class="slide-menu">
							<li><a class="slide-item" href="level1.php">level1</a></li>
							<li><a class="slide-item" href="level2.php">level2</a></li>
							<li><a class="slide-item" href="level3.php">level3</a></li>
			
						</ul>
					</li>
	
				    <li class="slide">
						<a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fe fe-bar-chart-2 menu-icon"></i><span class="side-menu__label">Learn Forex</span><span class="badge badge-info side-badge">1</span><i class="angle fe fe-chevron-down"></i></a>
						<ul class="slide-menu">
							<li><a class="slide-item" href="forex.php">Start Course</a></li>
						</ul>
					</li>
					
				    <li class="slide">
						<a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fe fe-play-circle menu-icon"></i><span class="side-menu__label">Watch Youtube</span><span class="badge badge-danger side-badge">2</span><i class="angle fe fe-chevron-down"></i></a>
						<ul class="slide-menu">
							<li><a class="slide-item" href="youtube">Watch</a></li>
							<li><a class="slide-item" href="youtube/?page=videoad&amp;x=myvids">MyVideos</a></li>
							<li><a class="slide-item" href="youtube/?page=videoad">Uploadvideo</a></li>
							
						</ul>
					</li>
					
				    <li class="slide">
						<a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fe fe-align-center menu-icon"></i><span class="side-menu__label">Trivia</span><span class="badge badge-primary side-badge">3</span><i class="angle fe fe-chevron-down"></i></a>
						<ul class="slide-menu">
							<li><a class="slide-item" href="trivia">Start</a></li>
							<li><a class="slide-item" href="triviahistory.php">Trivia History</a></li>
						</ul>
					</li>
					
				    <li class="slide">
						<a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fe fe fe-file-text menu-icon"></i><span class="side-menu__label">Blogs</span><span class="badge badge-success side-badge">4</span><i class="angle fe fe-chevron-down"></i></a>
						<ul class="slide-menu">
							<li><a class="slide-item" href="allblogs.php">All Blogs</a></li>
							<li><a class="slide-item" href="myblogs.php">My Blogs</a></li>
							<li><a class="slide-item" href="postblog.php">Post Blog</a></li>
						</ul>
					</li>
					
					<li class="slide">
						<a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fe fe-life-buoy menu-icon"></i><span class="side-menu__label">Spin</span><span class="badge badge-primary side-badge">5</span><i class="angle fe fe-chevron-down"></i></a>
						<ul class="slide-menu">
							<li><a class="slide-item" href="spin">Spin&amp;Win</a></li>
							<li><a class="slide-item" href="freespin">Free spin</a></li>
						</ul>
					</li>

		            <li class="slide">
						<a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fe fe-life-buoy menu-icon"></i><span class="side-menu__label">Buy Airtime</span><span class="badge badge-primary side-badge">6</span><i class="angle fe fe-chevron-down"></i></a>
						<ul class="slide-menu">
							<li><a class="slide-item" href="airtime.php">Buy Airtime</a></li>
							<li><a class="slide-item" href="airtimehistory.php">Airtime History</a></li>
						</ul>
					</li>
				    
				    <li class="slide">
				        
						<a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fe fe-menu menu-icon"></i><span class="side-menu__label">Ebooks</span><span class="badge badge-danger side-badge">7</span><i class="angle fe fe-chevron-down"></i></a>
						<ul class="slide-menu">
							<li><a class="slide-item" href="ebooks.php">Download</a></li>
		
						</ul>
					</li>
				    <li class="slide">
						<a class="side-menu__item" href="myprofile.php"><i class="side-menu__icon fe fe-user"></i><span class="side-menu__label">Profile</span></a>
					</li>
					<li class="slide">
						<a class="side-menu__item" href="contactus.php"><i class="side-menu__icon fe fe-phone-incoming"></i><span class="side-menu__label">ContactUs</span></a>
					</li>
				    <li class="slide">
						<a class="side-menu__item" href="logout.php"><i class="side-menu__icon fe fe-power"></i><span class="side-menu__label">Logout</span></a>
					</li>
				
					
			
				
			
				
			
				
				</ul>
			</div>
		<div class="ps__rail-x" style="left: 0px; top: 269px;"><div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps__rail-y" style="top: 269px; height: 695px; right: 0px;"><div class="ps__thumb-y" tabindex="0" style="top: 194px; height: 501px;"></div></div></aside>		<!-- main-sidebar closed -->

		<!-- main-content -->
		<div class="main-content">

			<!-- main-header -->
		   	<div class="main-header side-header">
				<div class="container-fluid">
					<div class="main-header-left ">
						<div class="app-sidebar__toggle mobile-toggle" data-toggle="sidebar">
							<a class="open-toggle" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="eva eva-menu-outline header-icons"><g data-name="Layer 2"><g data-name="menu"><rect width="24" height="24" transform="rotate(180 12 12)" opacity="0"></rect><rect x="3" y="11" width="18" height="2" rx=".95" ry=".95"></rect><rect x="3" y="16" width="18" height="2" rx=".95" ry=".95"></rect><rect x="3" y="6" width="18" height="2" rx=".95" ry=".95"></rect></g></g></svg></a>
							<a class="close-toggle" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="eva eva-close-outline header-icons"><g data-name="Layer 2"><g data-name="close"><rect width="24" height="24" transform="rotate(180 12 12)" opacity="0"></rect><path d="M13.41 12l4.3-4.29a1 1 0 1 0-1.42-1.42L12 10.59l-4.29-4.3a1 1 0 0 0-1.42 1.42l4.3 4.29-4.3 4.29a1 1 0 0 0 0 1.42 1 1 0 0 0 1.42 0l4.29-4.3 4.29 4.3a1 1 0 0 0 1.42 0 1 1 0 0 0 0-1.42z"></path></g></g></svg></a>
						</div>
						<div class="responsive-logo">
							<a href="index.html"><img src="assets//img/brand/logo-white.png" class="logo-1"></a>
							<a href="index.html"><img src="assets//img/brand/logo.png" class="logo-11"></a>
							<a href="index.html"><img src="assets//img/brand/favicon-white.png" class="logo-2"></a>
							<a href="index.html"><img src="assets//img/brand/favicon.png" class="logo-12"></a>
						</div>
						<ul class="header-megamenu-dropdown  nav">
							<li class="nav-item">
								<div class="btn-group dropdown">
									<button aria-expanded="false" aria-haspopup="true" class="btn btn-link dropdown-toggle" data-toggle="dropdown" id="dropdownMenuButton2" type="button"><span><i class="fe fe-settings"></i> Settings </span></button>
									<div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 5px, 0px);" x-out-of-boundaries="">
										<div class="dropdown-menu-header header-img p-3">
											<div class="drop-menu-inner">
												<div class="header-content text-left d-flex">
												    <div class="text-white">
														<h5 class="menu-header-title">Setting</h5>
														<h6 class="menu-header-subtitle mb-0">Overview of theme</h6>
													</div>
													<div class="my-auto ml-auto">
														<span class="badge badge-pill badge-warning float-right">View all</span>
													</div>
												</div>
											</div>
										</div>
										<div class="setting-scroll ps">
											<div>
												<div class="setting-menu ">
													<a class="dropdown-item" href="profile.php"><i class="mdi mdi-account-outline tx-16 mr-2 mt-1"></i>Profile</a>
													<a class="dropdown-item" href="contactus.php"><i class="mdi mdi-account-box-outline tx-16 mr-2"></i>Contacts</a>
													<a class="dropdown-item" href="#"><i class="mdi mdi-account-location tx-16 mr-2"></i>Accounts</a>
													<div class="dropdown-divider"></div>
													<a class="dropdown-item" href="#"><i class="typcn typcn-briefcase tx-16 mr-2"></i>About us</a>
													<a class="dropdown-item" href="#"><i class="mdi mdi-application tx-16 mr-2"></i>Getting start</a>
												</div>
											</div>
										<div class="ps__rail-x" style="left: 0px; top: 0px;"><div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps__rail-y" style="top: 0px; right: 0px;"><div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
										<ul class="setting-menu-footer flex-column pl-0">
											<li class="divider mb-0 pb-0 "></li>
											<li class="setting-menu-btn">
												<button class=" btn-shadow btn btn-success btn-sm">Cancel</button>
											</li>
										</ul>
									</div>
								</div>
							</li>
							<li class="nav-item">
								<div class="dropdown-menu-rounded btn-group dropdown">
									<button aria-expanded="false" aria-haspopup="true" class="btn btn-link dropdown-toggle" data-toggle="dropdown" id="dropdownMenuButton3" type="button"><span><i class="nav-link-icon fe fe-briefcase"></i> Projects </span></button>
									
								</div>
							</li>
					</ul></div>
					<div class="main-header-right">
						<div class="nav nav-item nav-link" id="bs-example-navbar-collapse-1">
							<form class="navbar-form" role="search">
								<div class="input-group">
									<input type="text" class="form-control" placeholder="Search">
									<span class="input-group-btn">
										<button type="reset" class="btn btn-default">
											<i class="fas fa-times"></i>
										</button>
										<button type="submit" class="btn btn-default nav-link">
											<i class="fe fe-search"></i>
										</button>
									</span>
								</div>
							</form>
						</div>
						<div class="nav nav-item  navbar-nav-right ml-auto">
							<div class="nav-item full-screen fullscreen-button">
								<a class="new nav-link full-screen-link" href="#"><i class="fe fe-maximize"></i></a>
							</div>
							<div class="dropdown nav-item main-header-message">
								<a class="new nav-link" href="#"><i class="fe fe-mail"></i><span class=" pulse-danger"></span></a>
							</div>
							<div class="dropdown nav-item main-header-notification">
								<a class="new nav-link" href="#"><i class="fe fe-bell"></i><span class=" pulse"></span></a>
					
							</div>
							<div class="dropdown main-profile-menu nav nav-item nav-link">

								<a class="profile-user d-flex" href=""><img src="assets//img/faces/6.jpg" alt="user-img" class="rounded-circle mCS_img_loaded"><span></span></a>

								<div class="dropdown-menu">
									<div class="main-header-profile header-img">
										<div class="main-img-user"><img alt="" src="assets//img/faces/6.jpg"></div>
										<h6 style="text-transform:capitalize;">sting</h6><span>Premium Member</span>
									</div>
									<a class="dropdown-item" href="profile.php"><i class="far fa-user"></i> My Profile</a>
									<a class="dropdown-item" href="contactus.php"><i class="far fa-edit"></i> Contact Us</a>
									<a class="dropdown-item" href="#"><i class="far fa-clock"></i> Activity Logs</a>
									<a class="dropdown-item" href="#"><i class="fas fa-sliders-h"></i> Account Settings</a>
									<a class="dropdown-item" href="logout.php"><i class="fas fa-sign-out-alt"></i> Sign Out</a>
								</div>
							</div>
							
						</div>
					</div>
				</div>
			</div>			<!-- /main-header -->

			<!-- container -->
			<div class="container-fluid">

				<!-- breadcrumb -->
				<div class="breadcrumb-header justify-content-between">
					<div>
						<h4 class="content-title mb-2">Hi, welcome <span style="text-transform:capitalize;">sting!</span></h4>
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="#">dashboard</a></li>
								<li class="breadcrumb-item active" aria-current="page"> dashboard</li>
							</ol>
						</nav>
					</div>
					<div class="d-flex my-auto">
						<div class=" d-flex right-page">
							<div class="d-flex justify-content-center mr-5">
								<div class="">
									<span class="d-block">
										<span class="label ">EXPENSES</span>
									</span>
									<span class="value">
										KSH 450									</span>
								</div>
								<div class="ml-3 mt-2">
									<span class="sparkline_bar"><canvas width="52" height="30" style="display: inline-block; width: 52px; height: 30px; vertical-align: top;"></canvas></span>
								</div>
							</div>
							<div class="d-flex justify-content-center">
								<div class="">
									<span class="d-block">
										<span class="label">PROFIT</span>
									</span>
									<span class="value">
									KSH 90									</span>
								</div>
								<div class="ml-3 mt-2">
									<span class="sparkline_bar31"><canvas width="52" height="30" style="display: inline-block; width: 52px; height: 30px; vertical-align: top;"></canvas></span>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- /breadcrumb -->

				<!-- row -->
				<div class="row row-sm">
					<div class="col-xl-3 col-lg-6 col-md-6 col-sm-12">
						<div class="card" style="background-image: linear-gradient(to bottom, #3ef67d 0, #bffccb 100%) !important;background-image: linear-gradient(to bottom, #a5f4b4 0, #53f58b 100%) !important;">
							<div class="card-body iconfont text-left">
								<div class="d-flex justify-content-between">
									<h4 class="card-title mb-3">BALANCE</h4>
									<i class="mdi mdi-dots-vertical"></i>
								</div>
								<div class="d-flex mb-0">
									<div class="">
										<h4 class="mb-1 font-weight-bold">KSH 40 </h4>
										<p class="mb-2 tx-12 text-muted">Your current Balance</p>
									</div>
									<div class="card-chart bg-primary-transparent brround ml-auto mt-0">
										<i class="typcn typcn-group-outline text-primary tx-24"></i>
									</div>
								</div>

								<div class="progress progress-sm mt-2">
									<div aria-valuemax="100" aria-valuemin="0" aria-valuenow="100" class="progress-bar bg-primary wd-100p" role="progressbar"></div>
								</div>
								<small class="mb-0  text-muted"><span class="float-right text-muted">100%</span></small>
							</div>
						</div>
					</div>
					<div class="col-xl-3 col-lg-6 col-md-6 col-sm-12">
						<div class="card" style="background-image: linear-gradient(to bottom, #eff0ce 0, #d4c80b 100%) !important;">
							<div class="card-body iconfont text-left">
								<div class="d-flex justify-content-between">
									<h4 class="card-title mb-3">WITHDRAWN</h4>
									<i class="mdi mdi-dots-vertical"></i>
								</div>
								<div class="d-flex mb-0">
									<div class="">
										<h4 class="mb-1 font-weight-bold">KSH 0 </h4>
										<p class="mb-2 tx-12 text-muted">Amount you have withdrawn</p>
									</div>
									<div class="card-chart bg-pink-transparent brround ml-auto mt-0">
										<i class="typcn typcn-chart-line-outline text-pink tx-24"></i>
									</div>
								</div>

								<div class="progress progress-sm mt-2">
									<div aria-valuemax="100" aria-valuemin="0" aria-valuenow="100" class="progress-bar bg-pink wd-100p" role="progressbar"></div>
								</div>
								<small class="mb-0  text-muted"><span class="float-right text-muted">100%</span></small>
							</div>
						</div>
					</div>
					<div class="col-xl-3 col-lg-6 col-md-6 col-sm-12">
						<div class="card" style="background-image: linear-gradient(to bottom, #719af6 0, #b0eaf4 100%) !important;">
							<div class="card-body iconfont text-left">
								<div class="d-flex justify-content-between">
									<h4 class="card-title mb-3">REFERRAL EARNINGS</h4>
									<i class="mdi mdi-dots-vertical"></i>
								</div>
								<div class="d-flex mb-0">
									<div class="">
										<h4 class="mb-1   font-weight-bold">KSH 0 </h4>
										<p class="mb-2 tx-12 text-muted">Overview of refferal Earnings</p>
									</div>
									<div class="card-chart bg-teal-transparent brround ml-auto mt-0">
										<i class="typcn typcn-chart-bar-outline text-teal tx-20"></i>
									</div>
								</div>

								<div class="progress progress-sm mt-2">
									<div aria-valuemax="100" aria-valuemin="0" aria-valuenow="100" class="progress-bar bg-teal wd-100p" role="progressbar"></div>
								</div>
								<small class="mb-0  text-muted"><span class="float-right text-muted">100%</span></small>
							</div>
						</div>
					</div>
				
				</div>
				<!-- /row -->

				<!-- row -->
				<div class="row row-sm">

					<div class="col-sm-12 col-md-6 col-lg-6 col-xl-3">
						<div class="card ">
							<div class="card-body" style="background: #f6e5e5 !important;">
								<div class="card-widget">
									<h6 class="mb-2">Youtube Earnings</h6>
									<h2 class="text-right"><i class="mdi mdi-cube icon-size float-left text-success text-success-shadow"></i><span>KSH 0 </span></h2>
									<p class="mb-0">Earned from Youtube<span class="float-right">$$$</span></p>
								</div>
							</div>
						</div>
					</div><!-- COL END -->
					<div class="col-sm-12 col-md-6 col-lg-6 col-xl-3">
						<div class="card" style="background: #c1f4c6 !important;">
							<div class="card-body">
								<div class="card-widget">
									<h6 class="mb-2">Trivia Earnings</h6>
									<h2 class="text-right"><i class="icon-size mdi mdi-poll-box   float-left text-warning text-warning-shadow"></i><span>KSH 50 </span></h2>
									<p class="mb-0">Earned from Trivia<span class="float-right">$$$</span></p>
								</div>
							</div>
						</div>
					</div><!-- COL END -->
					<div class="col-sm-12 col-md-6 col-lg-6 col-xl-3">
						<div class="card " style="background: #d6dbfa !important;">
							<div class="card-body">
								<div class="card-widget">
									<h6 class="mb-2">Blog Earnings</h6>
									<h2 class="text-right"><i class="fa fa-cart-plus icon-size float-left text-danger text-danger-shadow"></i><span>KSH 0 </span></h2>
									<p class="mb-0">Earned from Blogging<span class="float-right">$$$</span></p>
								</div>
							</div>
						</div>
					</div><!-- COL END -->
				</div>
				<!-- /row -->

		
				<div class="row row-sm">
				<div class="col-lg-12 col-md-12">
					<div class="card">
						<div class="card-body">
							<div class="main-content-label mg-b-5">
								Referral Link
							</div>
							<p class="mg-b-20">Click Copy to get your Referral Link</p>
				
								<div class="row row-xs">
									<div class="col-md-5">
									<input id="myInput" type="text" class="form-control" value="https://www.smarthela.com/register.php?ref=sting">
									</div>



									<div class="col-md mg-t-10 mg-md-t-0">
										<button type="submit" class="btn btn-main-primary btn-block" onclick="copyText()">Copy link</button>
								  <br>
									</div>
									
										    	<p class="mg-b-20">Or Click on the Icons to Share </p>
										<div class="col-md-6" style="font-size: 23px;">
										  
<div class="social-networks noprint">
<a href="https://api.whatsapp.com/send?text=https://www.smarthela.com/register.php?ref=sting" target="_blank"><i class="fab fa-whatsapp" aria-hidden="true" style="color: #25d366;padding-left: 12px;"></i></a>
<a href="https://twitter.com/share?text=Join Me&nbsp;Learn Forex!!, Watch and Earn ,, and many more only on Smarthela&amp;url=https://www.smarthela.com/register.php?ref=sting" target="_blank"><i class="fab fa-twitter" aria-hidden="true" style="color: #00aced;padding-left: 12px;"></i></a>
<a href="https://www.facebook.com/sharer.php?u=https://www.smarthela.com/register.php?ref=sting" target="_blank"><i class="fab fa-facebook" aria-hidden="true" style="color: #3b5998;padding-left: 12px;"></i></a>
<a href="mailto:?subject=Join Us&nbsp;Learn Forex!!, Watch and Earn ,, and many more only on Smarthela-https://www.smarthela.com/register.php?ref=sting" target="_blank"><i class="fas fa-envelope" aria-hidden="true" style="color: #bb001b;padding-left: 12px;"></i></a>
</div>	
</div>
								</div>
				
						</div>
					</div>
				</div>
			</div>
				<!-- row -->
			

				<!-- row -->
				<div class="row row-sm">
			
					<div class="col-md-12 col-lg-6 col-xl-4">
						<div class="card">
							<div class="card-header bg-transparent pd-b-0 pd-t-20 bd-b-0">
								<div class="d-flex justify-content-between">
									<h4 class="card-title mg-b-10">User Details</h4>
									<i class="mdi mdi-dots-vertical"></i>
								</div>
								<p class="tx-12 tx-gray-500 mb-0">Here are your user Details</p>
							</div>
							<div class="card-body">
								<ul class="sales-session mb-0">
									<li>
										<div class="d-flex justify-content-between">
											<h6>1. Username </h6>
											<p class="font-weight-semibold mb-2">sting</p>
										</div>
										<div class="progress  ht-5">
											<div aria-valuemax="100" aria-valuemin="0" aria-valuenow="50" class="progress-bar wd-25p bg-primary" role="progressbar"></div>
										</div>
									</li>
									<li>
										<div class="d-flex justify-content-between">
											<h6>2. Active Referrals</h6>
											<p class="font-weight-semibold mb-2">0</p>
										</div>
										<div class="progress  ht-5">
											<div aria-valuemax="100" aria-valuemin="0" aria-valuenow="50" class="progress-bar wd-50p bg-info" role="progressbar"></div>
										</div>
									</li>
									<li>
									<div class="d-flex justify-content-between">
										<h6>3. Email</h6>
										<p class="font-weight-semibold mb-2">ianmburusting@gmail.com</p>
									</div>
									<div class="progress  ht-5">
											<div aria-valuemax="100" aria-valuemin="0" aria-valuenow="60" class="progress-bar wd-75p bg-danger" role="progressbar"></div>
										</div>
									</li>
									<li>
										<div class="d-flex justify-content-between">
											<h6>4. Phone</h6>
											<p class="font-weight-semibold mb-2">254717519747</p>
										</div>
										<div class="progress  ht-5">
											<div aria-valuemax="100" aria-valuemin="0" aria-valuenow="50" class="progress-bar wd-100p bg-warning" role="progressbar"></div>
										</div>
									</li>
								
								</ul>
							</div>
						</div>
					</div>


					<div class="col-md-12 col-lg-6 col-xl-4">
						<div class="card">
							<div class="card-header bg-transparent pd-b-0 pd-t-20 bd-b-0">
								<div class="d-flex justify-content-between">
									<h4 class="card-title mg-b-10">Social Media Handles</h4>
									<i class="mdi mdi-dots-vertical"></i>
								</div>
								<p class="tx-12 tx-gray-500 mb-0">Follow us here</p>
							</div>
							<div class="card-body">
								
								<div class="main-profile-social-list">
									<div class="media">
										<div class="media-icon bg-primary-transparent text-primary">
											<i class="icon ion-logo-facebook"></i>
										</div>
										<div class="media-body">
											<span>Facebook</span> <a href="https://www.facebook.com/groups/473513784065602">https://www.facebook.com/groups/473513784065602  </a>
										</div>
									</div>
									<div class="media">
										<div class="media-icon bg-success-transparent text-success">
											<i class="icon ion-logo-twitter"></i>
										</div>
										<div class="media-body">
											<span>Twitter</span> <a href="https://twitter.com/Satoshiagencies">https://twitter.com/Satoshiagencies</a>
										</div>
									</div>
									<div class="media">
										<div class="media-icon bg-danger-transparent text-danger">
											<i class="icon ion-logo-instagram"></i>
										</div>
										<div class="media-body">
											<span>Instagram</span> <a href="https://www.instagram.com/satoshiagencies">https://www.instagram.com/satoshiagencies</a>
										</div>
									</div>
									<div class="media">
										<div class="media-icon bg-danger-transparent text-danger">
											<i class="icon ion-logo-youtube"></i>
										</div>
										<div class="media-body">
											<span>Youtube</span> <a href="https://www.youtube.com/channel/UCgOAf7snPf5JoC4L4sXNa_w">https://www.youtube.com/channel/UCgOAf7snPf5JoC4L4sXNa_w</a>
										</div>
									</div>
								</div>

							</div>
						</div>
					</div>

				</div>
				<!-- /row -->
			</div>
		</div>
		<!-- main-content closed -->

	

		<!-- Footer opened -->
       		<div class="main-footer ht-40">
			<div class="container-fluid pd-t-0-f ht-100p">
				<span>Copyright © 2021 <a href="#">SmartHela</a>. Designed by:<br> <a href="#">SMARTTHELA AGENCIES</a> All rights reserved.</span>
				
			</div>
		</div>		<!-- Footer closed -->
	</div>
		<!-- page closed -->

		<!--- Back-to-top --->
		<a href="#top" id="back-to-top" style="display: none;"><i class="las la-angle-double-up"></i></a>

	
                <script>
                function copyText() {
                /* Get the text field */
                var copyText = document.getElementById("myInput");
                
                /* Select the text field */
                copyText.select();
                copyText.setSelectionRange(0, 99999); /*For mobile devices*/
                
                /* Copy the text inside the text field */
                document.execCommand("copy");
                
                /* Alert the copied text */
                alert(copyText.value);
                alert('You have now copied your link you can now share it by pasting');
                
                }
                </script>

	
		<!--- JQuery min js --->
		<script src="assets//plugins/jquery/jquery.min.js"></script>

		<!--- Bootstrap Bundle js --->
		<script src="assets//plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

		<!--- Ionicons js --->
		<script src="assets//plugins/ionicons/ionicons.js"></script>

		<!--- Moment js --->
		<script src="assets//plugins/moment/moment.js"></script>

		<!--- Sparkline js --->
		<script src="assets//plugins/jquery-sparkline/jquery.sparkline.min.js"></script>

		<!--- Moment js --->
		<script src="assets//plugins/raphael/raphael.min.js"></script>

		<!-- Piety js -->
		<script src="assets//plugins/peity/jquery.peity.min.js"></script>


		<!--- P-scroll js --->
		<script src="assets//plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
		<script src="assets//plugins/perfect-scrollbar/p-scroll.js"></script>

		<!--- Internal Chart js --->
		<script src="assets//plugins/chart.js/Chart.bundle.min.js"></script>

		<!--- Rating js --->
		<script src="assets//plugins/rating/jquery.rating-stars.js"></script>
		<script src="assets//plugins/rating/jquery.barrating.js"></script>

		<!--- Custom Scroll bar Js --->
		<script src="assets//plugins/mscrollbar/jquery.mCustomScrollbar.concat.min.js"></script>

		<!--- Sidebar js --->
		<script src="assets//plugins/side-menu/sidemenu2.js"></script>

		<!--- Right-sidebar js --->
		<script src="assets//plugins/sidebar/sidebar.js"></script>
		<script src="assets//plugins/sidebar/sidebar-custom.js"></script>

		<!--- Eva icons js --->
		<script src="assets//js/eva-icons.min.js"></script>

		<!--- Index js --->
		<script src="assets//js/script.js"></script>

		<!--- Custom js --->
		<script src="assets//js/custom.js"></script>
		
		

	
<div class="main-navbar-backdrop"></div>
</body>
<script type="text/javascript" > </script>
</html>